# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db4141d870f82b0fdf82920d9d409159f72d135d3befd66e6dedbc824225291ffa04bdc47cd44b0400346f0d4135891b4c9c567fa0d2dc4e2365696c8d2ddaff

test:
  secret_key_base: 5d11d2689b089073c7e15b64dde16927eebf5f2c1c38e31540a1f5d1f27925f8c40292c3ee97eda76f1ca9c63ea65652ed65d8e577a328185bf77ddfe09a1026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
